language: python

python:
    - "3.4"
    - "3.3"
    - "2.7"

before_install:
    - pip install -r requirements.txt

install:
    - python setup.py install

script:
    - python setup.py test

notification:
    email: false
